<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_StateAllValve" Id="{416bcdfe-aa9b-46a2-89d5-9de465f90e80}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_StateAllValve : bool
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_StateAllValve:= GVL_IO_VALVE.DO_00_V01ChalcogenCarrierChange = false  or
				GVL_IO_VALVE.DO_00_V02MOCarreirChange = false  or
				GVL_IO_VALVE.DO_00_V03H2SeSourceChange = false  or
				GVL_IO_VALVE.DO_00_V04H2SSourceChange = false  or
				GVL_IO_VALVE.DO_00_V05Source_1TMInCarrierChange = false  or
				GVL_IO_VALVE.DO_00_V06Source_1TMInBypass = false  or
				GVL_IO_VALVE.DO_00_V07Source_2TMGaCarrierChange = false  or
				GVL_IO_VALVE.DO_00_V08Source_2TMGaBypass = false  or
				GVL_IO_VALVE.DO_00_V09Source_3DMSeCarrierChange = false  or
				GVL_IO_VALVE.DO_00_V10Source_3DMSeBypass = false  or
				GVL_IO_VALVE.DO_00_V11Source_4ChalcogenCarrierChange = false  or
				GVL_IO_VALVE.DO_00_V12Source_4ChalcogenBypass = false; ]]></ST>
    </Implementation>
    <LineIds Name="F_StateAllValve">
      <LineId Id="8" Count="11" />
    </LineIds>
  </POU>
</TcPlcObject>