<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="F_Variable_ToUI_InputState" Id="{ce868db6-6f39-41e0-a65d-161125454884}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Variable_ToUI_InputState: BOOL
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* UI Right Dashboard Variable*)
GVL_IO.aInputState[1].0 := GVL_IO_REACTOR_CABINET.DI_01_MaintenanceModeKey; //Maintenance Key
GVL_IO.aInputState[1].1	:= GVL_IO_REACTOR_CABINET.DO_06_ReactorCabinetLamp; //Reactor Cabinet Lamp
GVL_IO.aInputState[1].2	:= GVL_IO_GAS_CABINET.DO_07_GasCabinetLamp; // Gas Cabinet Lamp
GVL_IO.aInputState[1].3	:= GVL_IO_GAS_CABINET.DO_07_ControlCabinetLamp; // Power Cabinet Lamp
GVL_IO.aInputState[1].4 := GVL_IO_GAS_CABINET.DI_01_PneumaticPressureSensor; //CDA Alarm Switch
GVL_IO.aInputState[1].5	:=GVL_IO_REACTOR_CABINET.DI_02_C_WFlowSensor;  //Water Flow Sensor
GVL_IO.aInputState[1].6 := FALSE; //Induction Heater
GVL_IO.aInputState[1].7 := FALSE; //Induction Heater
GVL_IO.aInputState[1].8 := FALSE; //Induction Heater

//jhkang_  GVL_IO.aInputState[1].9	 , GVL_IO.aInputState[1].10 문의 필요
GVL_IO.aInputState[1].9	:=GVL_IO_REACTOR_CABINET.DO_05_SusceptorRotationSTOP; //Susceptor Rotation Motor
GVL_IO.aInputState[1].10:=GVL_IO_REACTOR_CABINET.DO_05_SusceptorRotationFWD; //Susceptor Rotation Motor
GVL_IO.aInputState[1].11:=GVL_IO_REACTOR_CABINET.DI_02_SusceptorRotationMotorFault; //Susceptor Rotation Motor
GVL_IO.aInputState[1].12 := GVL_IO_REACTOR_CABINET.DI_02_VacuumPumpWarning; //Vacuum Pump Warning
GVL_IO.aInputState[1].13 := GVL_IO_REACTOR_CABINET.DI_02_VacuumPumpRunning; //Vacuum Pump
GVL_IO.aInputState[1].14 := GVL_IO_REACTOR_CABINET.DI_02_VacuumPumpFail; //Vacuum Pump
GVL_IO.aInputState[1].15:= GVL_IO_REACTOR_CABINET.DI_03_ReactorCabinetDoorClose;
GVL_IO.aInputState[2].0	:= GVL_IO_GAS_CABINET.DI_01_GasCabinetDoorClose;
GVL_IO.aInputState[2].1	:= GVL_IO_GAS_CABINET.DI_01_ControlCabinetDoorClose;
GVL_IO.aInputState[2].2	:= GVL_IO_GAS_CABINET.DI_01_ResetButton;
GVL_IO.aInputState[2].3	:= GVL_IO_REACTOR_CABINET.DI_02_ReactorDoorUpLimitSensor;
GVL_IO.aInputState[2].4	:= GVL_IO_REACTOR_CABINET.DI_03_ReactorDoorDownLimitSensor;
GVL_IO.aInputState[2].5	:= NOT GVL_IO_GAS_CABINET.DI_01_SMPS_1Alarm;
GVL_IO.aInputState[2].6	:= NOT GVL_IO_GAS_CABINET.DI_01_SMPS_2Alarm;
GVL_IO.aInputState[2].7	:= NOT GVL_IO_GAS_CABINET.DI_01_SMPS_3Alarm;
GVL_IO.aInputState[2].8	:= NOT GVL_IO_GAS_CABINET.DI_02_SMPS_4Alarm;
GVL_IO.aInputState[2].9	:= GVL_IO_GAS_CABINET.DI_02_GraphiteHeaterELCB;
GVL_IO.aInputState[2].10:= GVL_IO_GAS_CABINET.DI_02_ThermalBathsELCB;
GVL_IO.aInputState[2].11:= GVL_IO_GAS_CABINET.DI_02_VacuumPumpELCB;
GVL_IO.aInputState[2].12:= GVL_IO_GAS_CABINET.DI_02_LineHeatersELCB;
GVL_IO.aInputState[2].13:= GVL_IO_GAS_CABINET.DI_02_RotationMotorCP;
GVL_IO.aInputState[2].14:= GVL_IO_GAS_CABINET.DI_02_CoverLiftMotorCP;
GVL_IO.aInputState[2].15:= GVL_IO_GAS_CABINET.DI_02_T_VCP;
GVL_IO.aInputState[3].0:= GVL_IO_GAS_CABINET.DI_03_CabinetLampsCP;
//jhkang 문서상에는 bsmps15cp 라고 나와있는데 MFCpowercp가 맞는지 확인
GVL_IO.aInputState[3].1:= GVL_IO_GAS_CABINET.DI_03_MFCPowerCP;
GVL_IO.aInputState[3].2:= GVL_IO_GAS_CABINET.DI_03_LineHeater_1CP;
GVL_IO.aInputState[3].3:= GVL_IO_GAS_CABINET.DI_03_LineHeater_2CP;
GVL_IO.aInputState[3].4:= GVL_IO_GAS_CABINET.DI_03_LineHeater_3CP;
GVL_IO.aInputState[3].5:= GVL_IO_GAS_CABINET.DI_03_LineHeater_4CP;
GVL_IO.aInputState[3].6:= GVL_IO_GAS_CABINET.DI_03_LineHeater_5CP;
GVL_IO.aInputState[3].7:= GVL_IO_GAS_CABINET.DI_04_LineHeater_6CP;
GVL_IO.aInputState[3].8:= GVL_IO_GAS_CABINET.DI_04_LineHeater_7CP;
GVL_IO.aInputState[3].9:= GVL_IO_GAS_CABINET.DI_04_LineHeater_8CP;
GVL_IO.aInputState[3].10:= GVL_IO_GAS_CABINET.DI_05_ThermalBath_1DeviationAlarm;
GVL_IO.aInputState[3].11:= GVL_IO_GAS_CABINET.DI_05_ThermalBath_2DeviationAlarm;
GVL_IO.aInputState[3].12:= GVL_IO_GAS_CABINET.DI_06_ThermalBath_3DeviationAlarm;
GVL_IO.aInputState[3].13:= GVL_IO_GAS_CABINET.DI_06_ThermalBath_4DeviationAlarm;

GVL_IO.aInputState[4].0:= GVL_IO_REACTOR_CABINET.DO_04_SignalTowerRed;
GVL_IO.aInputState[4].1:= GVL_IO_REACTOR_CABINET.DO_04_SignalTowerOrange;
GVL_IO.aInputState[4].2:= GVL_IO_REACTOR_CABINET.DO_04_SignalTowerGreen;
GVL_IO.aInputState[4].3:= GVL_IO_REACTOR_CABINET.DO_04_SignalTowerBlue;
GVL_IO.aInputState[4].4:= GVL_IO_REACTOR_CABINET.DO_04_SignalTowerWhite;
GVL_IO.aInputState[4].5:= GVL_IO_REACTOR_CABINET.DO_04_SignalTowerBuzzer;
GVL_IO.aInputState[4].6:= GVL_IO_GAS_CABINET.DI_04_GasDetectorH2;
GVL_IO.aInputState[4].7:= GVL_IO_GAS_CABINET.DI_04_GasDetectorH2S;
GVL_IO.aInputState[4].8:= GVL_IO_GAS_CABINET.DI_04_GasDetectorH2Se;
GVL_IO.aInputState[4].9:= GVL_IO_GAS_CABINET.DI_04_FireSensor;


GVL_IO.aInputState[5]:= GVL_DEVICE_NET_IQ_PLUS.nInputStatus;

GVL_IO.aInputState[6].4 := GVL_IO_REACTOR_CABINET.DI_02_VacuumPumpRunning;

GVL_IO.aInputState[6].5 := GVL_IO_GAS_CABINET.DI_04_ExternalScrubberFault;
GVL_IO.aInputState[6].6 := GVL_IO_GAS_CABINET.DI_05_ExternalH2GasCabinetFault;
GVL_IO.aInputState[6].7 := GVL_IO_GAS_CABINET.DI_05_ExternalH2SGasCabinetFault;
GVL_IO.aInputState[6].8 := GVL_IO_GAS_CABINET.DI_05_ExternalH2SeGasCabinetFault;
GVL_IO.aInputState[6].9 := GVL_IO_GAS_CABINET.DI_05_ExternalUserInputAlarm;


]]></ST>
    </Implementation>
    <LineIds Name="F_Variable_ToUI_InputState">
      <LineId Id="256" Count="35" />
      <LineId Id="347" Count="0" />
      <LineId Id="292" Count="0" />
      <LineId Id="348" Count="11" />
      <LineId Id="361" Count="0" />
      <LineId Id="360" Count="0" />
      <LineId Id="362" Count="5" />
      <LineId Id="370" Count="0" />
      <LineId Id="372" Count="0" />
      <LineId Id="385" Count="1" />
      <LineId Id="388" Count="0" />
      <LineId Id="375" Count="0" />
      <LineId Id="398" Count="0" />
      <LineId Id="389" Count="0" />
      <LineId Id="393" Count="0" />
      <LineId Id="392" Count="0" />
      <LineId Id="394" Count="3" />
      <LineId Id="374" Count="0" />
      <LineId Id="369" Count="0" />
      <LineId Id="82" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>